Parse and comment coverage in PR
HSU-HPC/MaMiCo pull request #34
Opened 2024-01-03 20:58 UTC by rubenhorn

2024-01-03 21:27 UTC, rubenhorn commented
Setting up python in the CI/CD [fails](https://github.com/HSU-HPC/MaMiCo/actions/runs/7402476642/job/20140417980) because caching pip packages is enabled.  
In order to fix this, the `lsb-release` package needs to be installed in the container image used in the CI/CD pipeline as described [here](https://github.com/actions/setup-python/issues/556#issuecomment-1336549877).

2024-01-04 20:12 UTC, rubenhorn commented
Works locally, but for some reason, the folder of the repository is empty after the Deploy step in the Doxygen Action. :man_shrugging:

2025-01-14 12:50 UTC, rubenhorn commented
Best to squash this when merging. :sweat_smile:

2025-01-23 16:06 UTC, Thinkpiet requested changes
Cool!

2025-01-23 16:06 UTC, Thinkpiet commented on .github/workflows/doxygen.yml
> +      - name: Doxygen Action
Why are there two copies of the step `Doxygen Action` here? Only one of them is guarded by the `if: github.event_name == 'push'`. Is this intended for some reason or would it accidentally update the documentation for non-merged PRs? (If it is intended, pls add a comment to explain it into the workflow file)

2025-01-23 16:06 UTC, Thinkpiet commented on .github/workflows/doxygen.yml
Expected runtime of this job is < 3 minutes. Can you add `timeout-minutes: 5` here ? Would be helpful e.g. if the script parsing the coverage gets stuck, so that it wouldn't accidentally consume our compute budget

2025-01-23 16:06 UTC, Thinkpiet commented on .github/workflows/doxygen.yml
Shouldn't this be restricted, e.g. to only run for `types: [review_requested, ready_for_review]` ?

If I create a draft PR to master, perhaps even for a something_WIP branch, then I certainly don't want this workflow to run automatically (getting coverage is not even possible for branches which are not even supposed to compile currently ...)

2025-01-23 16:06 UTC, Thinkpiet commented on test/check_my_coverage.py
> +    coverage_root = Path("build") / "coverage"
This assumes that the build folder is always called `build`, which might not be correct when this is called locally. I often have `build-testA` and `build-testB`. I think that `coverage_root` should be an input parameter of this script, defaulting to `Path(__file__).parent.parent / build / coverage`. I also think that there should be a cmake target  that calls `check_my_coverage.py` with the correct `coverage_root`

2025-01-23 16:06 UTC, Thinkpiet commented on test/check_my_coverage.py
> +    if not coverage_root.is_dir():
This assumes that the generated coverage data that is found here is recent, which might not be the case. It is not clear that one has to manually regenerate the coverage data before calling this script. Again, I think there should be a separate cmake target or it should be called directly from `make coverage`

2025-01-23 18:25 UTC, rubenhorn commented on .github/workflows/doxygen.yml
> +      - name: Doxygen Action
Looks like a bug from merging two versions of this file.

2025-03-20 14:34 UTC, Thinkpiet approved these changes
:rocket:

2025-03-20 14:39 UTC, merged