Refactor2402 wip
HSU-HPC/MaMiCo pull request #45
Opened 2024-02-23 05:06 UTC by Thinkpiet

For developers: https://github.com/HSU-HPC/MaMiCo/wiki/Index-Cheatsheet#indexing-refactoring-cheatsheet

2024-02-23 08:04 UTC, rubenhorn commented on ls1
Are these changes in the submodule directory intentional?

2024-02-23 20:35 UTC, Thinkpiet commented
All Done! @rubenhorn(?)

2024-02-23 20:36 UTC, Thinkpiet commented on ls1
Yes I they are (at least the latest one is)

2024-02-24 11:12 UTC, rubenhorn requested changes
I would recommend to simply remove all occurances of `@param indexConversion`.

The code looks good.
I verified that it can be compiled and that the tests pass.

However, the couette scenario with the example configuration in `couette.xml.template` does not run:
```
$ ../build/couette 
Run CouetteScenario...
Initialization: 2ms`
Finish CouetteScenario::initSolvers() 
ERROR simplemd::moleculemappings::VelocityStoermerVerletMapping::handleMolecule: Position 0 is out of range
Position: -nan , 30.6511 , 7.55553, molecule: 3135
Velocity: -nan , 0.189084 , 1.20591, molecule: 3135
OldVelocity: -1.48454 , 0.172614 , 1.31139, molecule: 3135
Force: -nan , 4.89854 , -14.1636, old: -9.08906 , 1.68924 , -28.0298
Old position: 22.0203 , 30.6501 , 7.54967
```
It still works as expected on the master branch. (Tag `legacyIndexing`)

2024-02-24 11:12 UTC, rubenhorn commented on coupling/NieVelocityImposition.h
> +   *  @param currentLocalCouplingCellIndex local linearised index of a coupling
This documentation is out of date. The function now takes a parameter called `globalCellIndex` (of type `CellIndex` with alias `I01`).

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/MoleculeExtractor.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/DeleteParticleMapping.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/PerturbateVelocityMapping.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/SetKineticEnergyMapping.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/SetMomentumMapping.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/SetTemperatureMapping.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/VTKMoleculePlotter.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/VelocityGradientRelaxationMapping.h
>      // std::cout << "Handle VelocityGradientRelaxation in cell " <<
Why did we refactor commented out code and not remove it/make the output conditional (debug mode)

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/VelocityGradientRelaxationMapping.h
> +      // THE CAKE IS A LIE
:)

“This was a triumph
I'm making a note here
Huge success
It's hard to overstate my satisfaction”

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/VelocityGradientRelaxationMapping.h
> +   *	@param currentLocalCouplingCellIndex
New parameter name is `cellIndex`

2024-02-24 11:12 UTC, rubenhorn commented on coupling/cell-mappings/ZhouBoundaryForce.h
>     *	@param cellIndex
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/indexing/Operations.h
> +#include <sstream>
I think this header might not be required _here_

2024-02-24 11:12 UTC, rubenhorn commented on coupling/interface/MDSolverInterface.h
>     *	@param indexConversion
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/sendrecv/FromMD2Macro.h
>     * 	@param indexConversion
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/sendrecv/FromMD2Macro.h
>     * 	@param indexConversion
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/sendrecv/FromMD2Macro.h
>     * 	@param indexConversion
Remove parameter from doc string

2024-02-24 11:12 UTC, rubenhorn commented on coupling/sendrecv/FromMD2Macro.h
>     * 	@param indexConversion
Remove parameters from doc string
(I'll stop commenting this from now on. Simply remove all of them :wink:)

2024-02-26 09:18 UTC, amartyads commented on coupling/indexing/Operations.h
> +#include <sstream>
i put it in debug since it's used in the debug output

2024-03-11 07:37 UTC, LouieVoit commented
I still get some issues when using MPI this time. Without domain decomposition (i.e. `<mpi-configuration number-of-processes="1 ; 1 ; 1" ></mpi-configuration>`), I get this error:
`ERROR coupling::SendReceiveBuffer::triggerSending(): Could not send from rank 0 to the same rank! No receive buffer available! Tag (in case of MPI; not used here): 500001`


When run with domain decomposition, with and without multi MD instances, I get this one:
`ERROR coupling::SendReceiveBuffer:triggerSending(): Send- and receive-buffer sizes do not match for information processed on same rank!
Recv-buffer size=378, send-buffer size=492`

2024-04-04 14:37 UTC, Thinkpiet commented
TODOS 

- [ ] Introduce the abstract class BaseCellContainer and the class FlexibleCellContainer. CellContainer and FlexibleCellContainer are subblasses of BaseCellContainer.
- [ ] The iterator in BaseCellContainer returns a std::pair<CellIndex, CouplingCell*>. std::tie shall be used to unpack the pair returned by the iterator.
- [ ] All the files in the sendrecv folder should be refactored
- [ ] In CouetteScenario.h:
    - [ ] Remove the CouplingBuffer structure and replace the send and receive buffers and indices by two FlexibleCellContainer
    - [ ] Rename sendBufffer and recvBuffer to respectively macroToMDBuffer and mdToMacroBuffer

2024-06-10 09:11 UTC, rubenhorn commented on test/unit/coupling/datastructures/FlexibleCellContainerTest.cpp
> +    // FlexibleCellContainer<3> container{couplingCells, idxs};
Why is there so much code commented out? Can this be removed?

2024-06-10 09:13 UTC, LouieVoit commented on test/unit/coupling/datastructures/FlexibleCellContainerTest.cpp
> +    // FlexibleCellContainer<3> container{couplingCells, idxs};
Yes. I will update the test. It's just temporary.

2024-08-07 14:34 UTC, rubenhorn commented
At [7dfabc0](https://github.com/HSU-HPC/MaMiCo/pull/45/commits/7dfabc094dfe9013a7a7c40336b1b649c4d0a447), the indexes being communicated (with 4 MPI ranks) match between [master](https://github.com/HSU-HPC/MaMiCo/pull/57) and the [refactor](https://github.com/HSU-HPC/MaMiCo/pull/59).

2024-08-08 15:15 UTC, rubenhorn commented on coupling/services/MultiMDCellService.h
> +      // FIXME Invalid cell container
See #30

2024-08-08 15:30 UTC, rubenhorn approved these changes
LGTM

2024-08-08 15:42 UTC, merged